kind: pipeline
type: docker
name: nodegoat

steps:
  - name: package
    image: openjdk:8
    commands:
    - tar -cvzf nodegoat-veracode.tar.gz --exclude=./nodegoat-veracode.tar.gz ./*
    - ls -lah
  
  - name: SAST
    image: openjdk:8
    commands:
    - ls -lah