name: security-action
on: [push]

jobs:
        
  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/upload-artifact@v2 
      with:
        path: veracode.zip
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - name: Unzip the Pipeline Scanner
      run: unzip -qq -n pipeline-scan-LATEST.zip
    - shell: bash
    - name: Veracode SAST - Pipeline Scan
      run: |
        java -jar pipeline-scan.jar --veracode_api_id "${{ secrets.VERACODE_ID }}" --veracode_api_key "${{ secrets.VERACODE_KEY }}" --file "veracode.zip" --fail_on_severity="Very High, High" --issue_details true
        
