name: security-action
on: [push]

jobs:   

  library-componets-security-analisys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
        
    - shell: bash
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/NodeGoat.git"
        export SRCCLR_SCM_REF=${{ github.workflow }}
        export SRCCLR_SCM_REF_TYPE="branch"
        export SRCCLR_SCM_REV=${{ github.run_id }}
        
        export EXTRA_ARGS='--update-advisor'
        curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS || true
        
  application-security:
    runs-on: ubuntu-latest
    needs: [library-componets-security-analisys]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
      with: 
        java-version: '8'
    - uses: actions/upload-artifact@v2 # Copy files from repository to docker container so the next uploadandscan action can access them.
      with:
        path: NodeGoat/veracode.zip # Wildcards can be used to filter the files copied into the container. See: https://github.com/actions/upload-artifact
    - run: ls -l

#    - name: Archive Release
#      uses: thedoctor0/zip-release@master
#      with:
#        filename: 'veracode.zip'
#        path: .

