name: security-action
on:
  push:
    branches: [feature-ejs]

jobs:

  Veracode-Software-Composition-Analisys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        export SRCCLR_SCM_REF=${{ github.workflow }}
        export SRCCLR_SCM_REF_TYPE="branch"
        export SRCCLR_SCM_REV=${{ github.run_id }}
        export SRCCLR_SCM_TYPE="GITHUB"
        export EXTRA_ARGS='--update-advisor --uri-as-name'

        curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan $EXTRA_ARGS
        
