name: security-action
on: [push]

jobs:

  Application-Packaging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .

  Veracode-Software-Composition-Analisys:
    runs-on: ubuntu-latest
    steps:  
    - shell: bash
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/NodeGoat.git"
        export SRCCLR_SCM_REF=${{ github.workflow }}
        export SRCCLR_SCM_REF_TYPE="branch"
        export SRCCLR_SCM_REV=${{ github.run_id }}
        
        export EXTRA_ARGS='--update-advisor'
        curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS || true
  
  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    needs: [Application-Packaging]
    steps:
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      env:
        VID: ${{ secrets.VID }}
        VKEY: ${{ secrets.VKEY }}
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - name: Unzip the Pipeline Scanner
      run: unzip pipeline-scan-LATEST.zip
    - name: Run Pipeline Scanner
      run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_ID}}" --veracode_api_key "${{secrets.VERACODE_KEY}}" --file "veracode.zip" --fail_on_severity="Very High, High" --issue_details

  Veracode-SAST-Policy-Scan:
    runs-on: ubuntu-latest
    needs: [Application-Packaging]
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
            
    - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
      with: 
        java-version: '8'
    - uses: actions/upload-artifact@v2 # Copy files from repository to docker container so the next uploadandscan action can access them.
      with:
        path: NodeGoat/veracode.zip # Wildcards can be used to filter the files copied into the container. See: https://github.com/actions/upload-artifact

    - uses: veracode/veracode-uploadandscan-action@master # Run the uploadandscan action. Inputs are described above.
      env:
        VID: ${{ secrets.VERACODE_ID }}
        VKEY: ${{ secrets.VERACODE_KEY }}
      with:
        vid: '$VERACODE_ID'
        vkey: '$VERACODE_KEY'
        criticality: 'VeryHigh'
        appname: 'NodeGoat-Demo'
        createprofile: true
        filepath: 'veracode.zip'
        deleteIncompleteScan: true
        version: ${{ github.run_id }}'
        scantimeout: 30
