name: security-action
on: [push]

jobs:
        
  Veracode-SAST-Pipeline-Scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/upload-artifact@v2 
      with:
        path: veracode.zip
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq pipeline-scan-LATEST.zip -d .
    - shell: bash
      env:
        VID: ${{ secrets.VID }}
        VKEY: ${{ secrets.VKEY }}
      run: |
        ls -l
        
