name: security-action
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        #exclusions: '*.git* /*node_modules/* .editorconfig'
        
  application-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -l
        
     # - uses: actions/setup-node@v1
     # - run: npm install -g bats
     # - run: bats -v
