name: security-action
on: [push]

jobs:   

  library-componets-security-analisys:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'veracode.zip'
        path: .
        
    - shell: bash
      env:
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: |
        export SRCCLR_SCM_URI="https://github.com/lucasferreiram3/NodeGoat.git"
        export SRCCLR_SCM_REF=${{ github.workflow }}
        export SRCCLR_SCM_REF_TYPE="branch"
        export SRCCLR_SCM_REV=${{ github.run_id }}
        
        export EXTRA_ARGS='--update-advisor'
        curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS
